backend:
  name: github
  repo: integrityph/luks-ph-cms
  branch: main
media_folder: "public/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/static/images/uploads" 
collections:
  - name: "categories"
    label: "Categories"
    folder: src/content/categories
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Banner"
        name: "banner"
        widget: "object"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - label: "Photo"
        name: "photo"
        widget: "object"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - label: "Icon"
        name: "icon"
        widget: "object"
        fields:
          - { label: "Source", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
      - { label: "NISFL", name: "nisfl", widget: "boolean" }
      - { label: "Status", name: "status", widget: "boolean" }
  - name: "services"
    label: "Services"
    folder: src/content/services
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Status", name: "status", widget: "boolean" }